import type { NextPage } from 'next'
import Head from 'next/head'
import Repositories from "../components/Repositories";

const Home: NextPage = () => {
  return (
    <div className="body">
      <Head>
        <title>Search GitHub Repos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='header'> <h1>Search Git Hub Repos</h1></div>
        <Repositories />
    </div>
  )
}

export default Home
